# HEX в таком стиле: #FFFFF или §x§E§9§6§B§6§B

time-clear-item: 120 # Сколько времени будет лежать предмет, перед тем, как очиститься. Указывать в секундах
item-text: "&c❌ %time%" # Текст над предметом, который будет очищен

messages:
  on-clear-message: "&aВы очистили всё с пола!"
  usage-message: "&fУкажите что вы хотите сделать: &a/hic clear"
  no-permission: "&cНет прав на данную команду!"

particle-settings:
  use-particle-on-clear: true # Использовать ли партиклы прыи очистке предмета
  particle-type: "CRIT" # Тип партикла при исчезновении предмета
  particle-count: 10 # Кол-во партиклов
  offset-x: 0 # Смещение партикла по x координате
  offset-y: 0 # Смещение партикла по y координате
  offset-z: 0 # Смещение партикла по z координате
