name: HoloItemClear
version: '1.1.1'
main: io.wisp.holoitemclear.Main
api-version: '1.16'
permissions:
  holoitemclear.admin:
    description: Позволяет использовать команды holoitemclear
commands:
  holoitemclear:
    usage: /holoitemclear
    aliases:
      - hic
      - itemclear
